name: cron
on:
    push:
        branches:
            - main
    pull_request:
    schedule:
        - cron: "0 2 1 * *"

jobs:
    acme:
        name: Update via acme.sh
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install Python dependencies
              uses: py-actions/py-dependency-install@v2
            - name: Update
              uses: nick-invision/retry@v2
              with:
                  shell: bash
                  retry_on: error
                  timeout_minutes: 31
                  max_attempts: 3
                  command: docker run --rm -i -e Namesilo_Key=${{ secrets.NAMESILO_KEY }} -v "$(pwd)/out":/acme.sh neilpang/acme.sh --issue --dns dns_namesilo --dnssleep 1800 -d ${{ secrets.DOMAIN }} --quiet
            - name: deploy
              shell: bash
              env:
                  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
                  SECRET_KEY: ${{ secrets.SECRET_KEY }}
                  DOMAIN: ${{ secrets.DOMAIN }}
              run: python $(pwd)/update_cdn_sslcert.py
